import 'package:envied/envied.dart';

part 'env.g.dart';

/// Build-time configuration injected from `.env` (see also `.env.dev`,
/// `.env.prod`).
///
/// Only PUBLIC client configuration (Firebase client options, Agora app id,
/// Cloudinary cloud name/presets) lives here — A-class values from the Phase 0
/// audit. Real secrets (Agora App Certificate, Firebase Admin service account)
/// are intentionally NOT in Envied: obfuscation does not make values
/// unrecoverable from the packaged app, so those must move to a backend in a
/// later phase (P3/P4) and be rotated.
///
/// Generated by: `dart run build_runner build --delete-conflicting-outputs`
@Envied(path: '.env', obfuscate: true)
abstract class AppEnv {
  @EnviedField(varName: 'FIREBASE_ANDROID_API_KEY')
  static final String firebaseAndroidApiKey = _AppEnv.firebaseAndroidApiKey;

  @EnviedField(varName: 'FIREBASE_ANDROID_APP_ID')
  static final String firebaseAndroidAppId = _AppEnv.firebaseAndroidAppId;

  @EnviedField(varName: 'FIREBASE_IOS_API_KEY')
  static final String firebaseIosApiKey = _AppEnv.firebaseIosApiKey;

  @EnviedField(varName: 'FIREBASE_IOS_APP_ID')
  static final String firebaseIosAppId = _AppEnv.firebaseIosAppId;

  @EnviedField(varName: 'FIREBASE_MESSAGING_SENDER_ID')
  static final String firebaseMessagingSenderId =
      _AppEnv.firebaseMessagingSenderId;

  @EnviedField(varName: 'FIREBASE_PROJECT_ID')
  static final String firebaseProjectId = _AppEnv.firebaseProjectId;

  @EnviedField(varName: 'FIREBASE_STORAGE_BUCKET')
  static final String firebaseStorageBucket = _AppEnv.firebaseStorageBucket;

  @EnviedField(varName: 'AGORA_APP_ID')
  static final String agoraAppId = _AppEnv.agoraAppId;

  @EnviedField(varName: 'CLOUDINARY_CLOUD_NAME')
  static final String cloudinaryCloudName = _AppEnv.cloudinaryCloudName;

  @EnviedField(varName: 'CLOUDINARY_IMAGE_PRESET')
  static final String cloudinaryImagePreset = _AppEnv.cloudinaryImagePreset;

  @EnviedField(varName: 'CLOUDINARY_VIDEO_PRESET')
  static final String cloudinaryVideoPreset = _AppEnv.cloudinaryVideoPreset;

  @EnviedField(varName: 'CLOUDINARY_VOICE_PRESET')
  static final String cloudinaryVoicePreset = _AppEnv.cloudinaryVoicePreset;

  @EnviedField(varName: 'BREVO_API_KEY')
  static final String brevoApiKey = _AppEnv.brevoApiKey;
}